# this file is just to make it easier to build the container to then use in k8s -> docker compose build

services:
   app:
    build:
      context: .
      dockerfile: ./src/MonitorApp/Dockerfile
    image: discoveryviakubernetesapisample/monitor:latest