apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx-1
  template:
    metadata:
      labels:
        app: sample-nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nginx-service-1
  annotations:
    some-sample-annotation: "this is sample nginx service 1"
spec:
  selector:
    app: sample-nginx-1
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 80